# Generated by Django 4.2.2 on 2023-09-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('noticias', 'Notícias'), ('como_fazer', 'Como Fazer'), ('review', 'Review')], default=None, max_length=15, null=True, verbose_name='Categoria'),
        ),
    ]
